Imported rigged possum player model
EmileDavidson/Examen pull request #13
Opened 2023-03-31 10:05 UTC by neon-pixel

2023-04-05 10:27 UTC, GodlyHamster requested changes

2023-04-05 10:27 UTC, GodlyHamster commented on ExamenProeveUnity/Assets/Art/Textures/Possum/PossumUV_lambert1_BaseColor.png
Naam van asset klopt niet met naming conventions
Textures gebruiken als prefix 'T_' en albedo's gebruiken '_A' als suffix
Correctere naam zou zijn: 'T_Possum_A'

2023-04-05 10:27 UTC, GodlyHamster commented on ExamenProeveUnity/Assets/Art/Textures/Possum/PossumUV_EyeR_BaseColor.png
Naam van asset klopt niet met naming conventions
Textures gebruiken als prefix 'T_' en albedo's gebruiken '_A' als suffix
Correctere naam zou zijn: 'T_PossumEyeR_A'

2023-04-05 10:27 UTC, GodlyHamster commented on ExamenProeveUnity/Assets/Art/Textures/Possum/PossumUV_EyeL_BaseColor.png
Naam van asset klopt niet met naming conventions
Textures gebruiken als prefix 'T_' en albedo's gebruiken '_A' als suffix
Correctere naam zou zijn: 'T_PossumEyeL_A'

2023-04-12 09:30 UTC, EmileDavidson approved these changes

2023-04-12 09:31 UTC, EmileDavidson approved these changes

2023-04-12 09:31 UTC, EmileDavidson approved these changes

2023-04-12 09:33 UTC, merged