Feature/feedback improvements
EmileDavidson/Examen pull request #80
Opened 2023-05-30 16:50 UTC by EmileDavidson

2023-05-30 17:23 UTC, GodlyHamster requested changes

2023-05-30 17:23 UTC, GodlyHamster commented on ExamenProeveUnity/Assets/Scripts/Runtime/Managers/PlayerManager.cs
> +            return _playerInputs;
De eerste return is niet nodig?

2023-05-30 17:23 UTC, GodlyHamster commented on ExamenProeveUnity/Assets/Scripts/Runtime/Player/PlayerInputEvents.cs
> +        }
De grabs invoken dezelfde event als de shoulder buttons
Zou onRightGrab en onLeftGrab niet beter zijn?

2023-06-01 09:22 UTC, EmileDavidson commented on ExamenProeveUnity/Assets/Scripts/Runtime/Player/PlayerInputEvents.cs
> +        }
Maybe maar ik heb ze ook onder de andere control scheme toegevoegd en wil eigenlijk gewoon weten welke button ik press

2023-06-01 12:05 UTC, GodlyHamster approved these changes

2023-06-01 12:05 UTC, merged